name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: anonja/js-web-app

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.sha }}
      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker buildx build \
            --platform linux/arm64/v8 \
            --tag $IMAGE_NAME:$SHORT_SHA \
            --push \
            .