name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: anonja/js-web-app

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.sha }}
      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker buildx build \
            --platform linux/arm64/v8 \
            --tag $IMAGE_NAME:$SHORT_SHA \
            --push \
            .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Clone another repo
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #   run: |
      #     git clone https://${GITHUB_TOKEN}@github.com/Mathpro1412/platform-k8s-app-overlays.git
      #     cd platform-k8s-app-overlays/apps/prod
      #     git checkout main
      - name: Clone another repo
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://${GITHUB_TOKEN}@github.com/Mathpro1412/nong-kai-helm-charts.git
          cd nong-kai-helm-charts/prod
          git checkout main
      - name: Install yq (Linux binary)
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      - name: Verify yq version
        run: |
          yq --version
      # - name: Update image tag
      #   run: |
      #     SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
      #     yq -i '.images[0].newTag = "'"$SHORT_SHA"'"' platform-k8s-app-overlays/apps/prod/kustomization.yaml
      - name: Update image tag
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          yq -i '.image.tag = "'"$SHORT_SHA"'"' nong-kai-helm-charts/prod/custom.yaml
      - name: Commit and Push
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cd nong-kai-helm-charts
      
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          git remote set-url origin https://${GH_TOKEN}@github.com/Mathpro1412/nong-kai-helm-charts.git
      
          git add prod/custom.yaml
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          git commit -m "ci: update image to anonja/js-web-app:${SHORT_SHA}" || echo "No changes"
          git push origin main