name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: anonja/js-web-app

    steps:
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.sha }}
      - name: Set up Docker Buildx
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker buildx build \
            --platform linux/arm64/v8 \
            --tag $IMAGE_NAME:$SHORT_SHA \
            --push \
            .
      - name: Clone another repo
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://${GITHUB_TOKEN}@github.com/Mathpro1412/platform-k8s-app-config-prod.git
          cd platform-k8s-app-config-prod/manifests
          git checkout main
      - name: Install yq (Linux binary)
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      - name: Verify yq version
        run: |
          yq --version
      - name: Update image tag
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          yq -i '.spec.template.spec.containers[0].image = "anonja/js-web-app:'"$SHORT_SHA"'"' platform-k8s-app-config-prod/manifests/deployment.yaml
      - name: Show updated YAML (for debug)
        run: cat platform-k8s-app-config-prod/manifests/deployment.yaml
      - name: Commit and Push
        run: |
          cd platform-k8s-app-config-prod
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add manifests/deployment.yaml
          git commit -m "ci: update image to anonja/js-web-app:${SHORT_SHA}"
          git push origin main